// java-projects/JtProject-Vue/frontend/src/components/AdminAuthForm.vue
<script setup lang="ts">
const props = defineProps<{
  message: string
  adminLogin: { username: string; password: string }
}>()

defineEmits<{
  login: []
}>()
</script>

<template>
  <p class="banner">{{ props.message }}</p>
  <div class="stack">
    <input v-model="props.adminLogin.username" placeholder="Admin username" />
    <input v-model="props.adminLogin.password" type="password" placeholder="Admin password" />
    <button @click="$emit('login')">管理员登录</button>
  </div>
</template>

// java-projects/JtProject-React/frontend/src/components/AdminAuthForm.tsx
import type { FormEvent } from 'react'
import type { AdminLoginForm } from '../services/appService'

type Props = {
  message: string
  adminLogin: AdminLoginForm
  setAdminLogin: (value: AdminLoginForm) => void
  onLogin: (event: FormEvent) => void
}

export function AdminAuthForm({ message, adminLogin, setAdminLogin, onLogin }: Props) {
  return (
    <>
      <p className="banner">{message}</p>
      <form onSubmit={onLogin} className="form">
        <input value={adminLogin.username} onChange={(e) => setAdminLogin({ ...adminLogin, username: e.target.value })} placeholder="Admin username" />
        <input value={adminLogin.password} type="password" onChange={(e) => setAdminLogin({ ...adminLogin, password: e.target.value })} placeholder="Admin password" />
        <button type="submit">管理员登录</button>
      </form>
    </>
  )
}
