// java-projects/JtProject-Vue/frontend/src/components/CartList.vue
<script setup lang="ts">
import type { Product } from '../types'

defineProps<{
  cart: Product[]
}>()

defineEmits<{
  remove: [productId: number]
}>()
</script>

<template>
  <div class="stack">
    <div v-for="(product, index) in cart" :key="`${product.id}-${index}`" class="list-row">
      <div>
        <strong>{{ product.name }}</strong>
        <p>{{ product.categoryName }}</p>
      </div>
      <button class="ghost" @click="$emit('remove', product.id)">Remove</button>
    </div>
  </div>
</template>

// java-projects/JtProject-React/frontend/src/components/CartList.tsx
import type { Product } from '../types'

type Props = {
  cart: Product[]
  onRemove: (productId: number) => void
}

export function CartList({ cart, onRemove }: Props) {
  return (
    <div className="stack">
      {cart.map((product, index) => (
        <div key={`${product.id}-${index}`} className="listRow">
          <div>
            <strong>{product.name}</strong>
            <p>{product.categoryName}</p>
          </div>
          <button className="ghost" onClick={() => onRemove(product.id)}>Remove</button>
        </div>
      ))}
    </div>
  )
}
