// java-projects/JtProject-Vue/frontend/src/components/CategoryManager.vue
<script setup lang="ts">
import type { Category } from '../types'

const props = defineProps<{
  categories: Category[]
  categoryForm: { id: number; name: string }
}>()

defineEmits<{
  submit: []
  edit: [category: Category]
  delete: [id: number]
}>()
</script>

<template>
  <article class="panel">
    <h2>Category Studio</h2>
    <div class="stack">
      <input v-model="props.categoryForm.name" placeholder="Category name" />
      <button @click="$emit('submit')">{{ props.categoryForm.id ? 'Update Category' : 'Create Category' }}</button>
    </div>
    <div class="stack">
      <div v-for="category in props.categories" :key="category.id" class="list-row">
        <span>{{ category.name }}</span>
        <div class="actions">
          <button class="ghost" @click="$emit('edit', category)">Edit</button>
          <button class="ghost" @click="$emit('delete', category.id)">Delete</button>
        </div>
      </div>
    </div>
  </article>
</template>

// java-projects/JtProject-React/frontend/src/components/CategoryManager.tsx
import type { FormEvent } from 'react'
import type { Category } from '../types'

type Props = {
  categories: Category[]
  categoryForm: { id: number; name: string }
  setCategoryForm: (value: { id: number; name: string }) => void
  onSubmit: (event: FormEvent) => void
  onDelete: (id: number) => void
}

export function CategoryManager({ categories, categoryForm, setCategoryForm, onSubmit, onDelete }: Props) {
  return (
    <article className="panel">
      <h2>Categories</h2>
      <form onSubmit={onSubmit} className="form">
        <input value={categoryForm.name} onChange={(e) => setCategoryForm({ ...categoryForm, name: e.target.value })} placeholder="Category name" />
        <button type="submit">{categoryForm.id ? 'Update Category' : 'Create Category'}</button>
      </form>
      <div className="stack">
        {categories.map((category) => (
          <div key={category.id} className="listRow">
            <span>{category.name}</span>
            <div className="inlineActions">
              <button className="ghost" onClick={() => setCategoryForm(category)}>Edit</button>
              <button className="ghost" onClick={() => onDelete(category.id)}>Delete</button>
            </div>
          </div>
        ))}
      </div>
    </article>
  )
}
