// java-projects/JtProject-Vue/frontend/src/components/CustomerList.vue
<script setup lang="ts">
import type { User } from '../types'

defineProps<{
  customers: User[]
}>()
</script>

<template>
  <article class="panel">
    <h2>Customers</h2>
    <div class="stack">
      <div v-for="customer in customers" :key="customer.id" class="list-row">
        <div>
          <strong>{{ customer.username }}</strong>
          <p>{{ customer.email }} / {{ customer.role }}</p>
        </div>
        <span>{{ customer.address }}</span>
      </div>
    </div>
  </article>
</template>

// java-projects/JtProject-React/frontend/src/components/CustomerList.tsx
import type { User } from '../types'

export function CustomerList({ customers }: { customers: User[] }) {
  return (
    <article className="panel">
      <h2>Customers</h2>
      <div className="stack">
        {customers.map((customer) => (
          <div key={customer.id} className="listRow">
            <div>
              <strong>{customer.username}</strong>
              <p>{customer.email} / {customer.role}</p>
            </div>
            <span>{customer.address}</span>
          </div>
        ))}
      </div>
    </article>
  )
}
