// java-projects/JtProject-Vue/frontend/src/components/ProfileEditor.vue
<script setup lang="ts">
const props = defineProps<{
  profileForm: { username: string; email: string; password: string; address: string }
}>()

defineEmits<{
  submit: []
}>()
</script>

<template>
  <article class="panel">
    <h2>Admin Profile</h2>
    <div class="stack">
      <input v-model="props.profileForm.username" placeholder="Username" />
      <input v-model="props.profileForm.email" placeholder="Email" />
      <input v-model="props.profileForm.password" placeholder="Password" />
      <input v-model="props.profileForm.address" placeholder="Address" />
      <button @click="$emit('submit')">Update Profile</button>
    </div>
  </article>
</template>

// java-projects/JtProject-React/frontend/src/components/ProfileEditor.tsx
import type { FormEvent } from 'react'

type Props = {
  profileForm: { username: string; email: string; password: string; address: string }
  setProfileForm: (value: { username: string; email: string; password: string; address: string }) => void
  onSubmit: (event: FormEvent) => void
}

export function ProfileEditor({ profileForm, setProfileForm, onSubmit }: Props) {
  return (
    <article className="panel">
      <h2>Admin Profile</h2>
      <form onSubmit={onSubmit} className="form">
        <input value={profileForm.username} onChange={(e) => setProfileForm({ ...profileForm, username: e.target.value })} placeholder="Username" />
        <input value={profileForm.email} onChange={(e) => setProfileForm({ ...profileForm, email: e.target.value })} placeholder="Email" />
        <input value={profileForm.password} onChange={(e) => setProfileForm({ ...profileForm, password: e.target.value })} placeholder="Password" />
        <input value={profileForm.address} onChange={(e) => setProfileForm({ ...profileForm, address: e.target.value })} placeholder="Address" />
        <button type="submit">Update Profile</button>
      </form>
    </article>
  )
}
