// java-projects/JtProject-Vue/frontend/src/views/ProductsView.vue
<script setup lang="ts">
import PageHeader from '../components/PageHeader.vue'
import ProductGrid from '../components/ProductGrid.vue'
import { useAppStore } from '../composables/useAppStore'

const { addToCart, store } = useAppStore()
</script>

<template>
  <section class="page-section">
    <article class="panel">
      <PageHeader
        eyebrow="Products"
        title="商品页"
        subtitle="对应原项目里的 `index.jsp` 和 `uproduct.jsp`。"
        :message="store.message"
        :meta="`User: ${store.session.authenticated ? store.session.username : 'guest'}`"
      />
      <ProductGrid :products="store.products" @add-to-cart="addToCart" />
    </article>
  </section>
</template>

// java-projects/JtProject-React/frontend/src/views/ProductsView.tsx
import { PageHeader } from '../components/PageHeader'
import { ProductGrid } from '../components/ProductGrid'
import type { Product, Session } from '../types'

type Props = {
  session: Session
  products: Product[]
  message: string
  onAddToCart: (productId: number) => void
}

export function ProductsView({ session, products, message, onAddToCart }: Props) {
  return (
    <section className="pageSection">
      <article className="panel">
        <PageHeader
          eyebrow="Products"
          title="商品页"
          subtitle="对应原项目里的 `index.jsp` 和 `uproduct.jsp`。"
          message={message}
          meta={`User: ${session.authenticated ? session.username : 'guest'}`}
        />
        <ProductGrid products={products} onAddToCart={onAddToCart} />
      </article>
    </section>
  )
}
