// java-projects/JtProject-React/frontend/src/views/AdminDashboardView.tsx
import type { FormEvent } from 'react'
import { CategoryManager } from '../components/CategoryManager'
import { CustomerList } from '../components/CustomerList'
import { PageHeader } from '../components/PageHeader'
import { ProductManager } from '../components/ProductManager'
import { ProfileEditor } from '../components/ProfileEditor'
import type { Category, Overview, Product, User } from '../types'

type ProductForm = {
  id: number
  name: string
  categoryId: number
  price: number
  weight: number
  quantity: number
  description: string
  image: string
}

type Props = {
  message: string
  overview: Overview | null
  categories: Category[]
  products: Product[]
  customers: User[]
  profileForm: { username: string; email: string; password: string; address: string }
  categoryForm: { id: number; name: string }
  productForm: ProductForm
  setCategoryForm: (value: { id: number; name: string }) => void
  setProductForm: (value: ProductForm) => void
  setProfileForm: (value: { username: string; email: string; password: string; address: string }) => void
  onSubmitCategory: (event: FormEvent) => void
  onDeleteCategory: (id: number) => void
  onSubmitProduct: (event: FormEvent) => void
  onDeleteProduct: (id: number) => void
  onSubmitProfile: (event: FormEvent) => void
}

export function AdminDashboardView(props: Props) {
  const { message, overview } = props

  return (
    <section className="pageSection">
      <article className="panel">
        <PageHeader
          eyebrow="Admin Dashboard"
          title="管理后台页"
          subtitle="对应原项目里的 `adminHome.jsp`、`categories.jsp`、`products.jsp`、`displayCustomers.jsp`、`updateProfile.jsp`。"
          message={message}
          meta={overview?.adminUsername}
        />
        {overview ? (
          <div className="chips">
            <span>{overview.categoryCount} categories</span>
            <span>{overview.productCount} products</span>
            <span>{overview.customerCount} customers</span>
          </div>
        ) : null}
      </article>

      <section className="grid wide">
        <CategoryManager
          categories={props.categories}
          categoryForm={props.categoryForm}
          setCategoryForm={props.setCategoryForm}
          onSubmit={props.onSubmitCategory}
          onDelete={props.onDeleteCategory}
        />
        <ProductManager
          categories={props.categories}
          products={props.products}
          productForm={props.productForm}
          setProductForm={props.setProductForm}
          onSubmit={props.onSubmitProduct}
          onDelete={props.onDeleteProduct}
        />
      </section>

      <section className="grid wide">
        <CustomerList customers={props.customers} />
        <ProfileEditor profileForm={props.profileForm} setProfileForm={props.setProfileForm} onSubmit={props.onSubmitProfile} />
      </section>
    </section>
  )
}

// java-projects/JtProject-Vue/frontend/src/views/AdminDashboardView.vue
<script setup lang="ts">
import CategoryManager from '../components/CategoryManager.vue'
import CustomerList from '../components/CustomerList.vue'
import PageHeader from '../components/PageHeader.vue'
import ProductManager from '../components/ProductManager.vue'
import ProfileEditor from '../components/ProfileEditor.vue'
import { useAppStore } from '../composables/useAppStore'

const { deleteCategory, deleteProduct, fillCategoryForm, fillProductForm, saveCategory, saveProduct, saveProfile, store } = useAppStore()
</script>

<template>
  <section class="page-section">
    <article class="panel">
      <PageHeader
        eyebrow="Admin Dashboard"
        title="管理后台页"
        subtitle="对应原项目里的 `adminHome.jsp`、`categories.jsp`、`products.jsp`、`displayCustomers.jsp`、`updateProfile.jsp`。"
        :message="store.message"
        :meta="store.overview?.adminUsername"
      />
      <div v-if="store.overview" class="stats">
        <span>{{ store.overview.categoryCount }} categories</span>
        <span>{{ store.overview.productCount }} products</span>
        <span>{{ store.overview.customerCount }} customers</span>
      </div>
    </article>

    <section class="board wide">
      <CategoryManager
        :categories="store.categories"
        :category-form="store.categoryForm"
        @submit="saveCategory"
        @edit="fillCategoryForm"
        @delete="deleteCategory"
      />
      <ProductManager
        :categories="store.categories"
        :products="store.products"
        :product-form="store.productForm"
        @submit="saveProduct"
        @edit="fillProductForm"
        @delete="deleteProduct"
      />
    </section>

    <section class="board wide">
      <CustomerList :customers="store.customers" />
      <ProfileEditor :profile-form="store.profileForm" @submit="saveProfile" />
    </section>
  </section>
</template>
