// java-projects/JtProject-React/frontend/src/components/PageHeader.tsx
type Props = {
  eyebrow: string
  title: string
  subtitle: string
  message: string
  meta?: string
}

export function PageHeader({ eyebrow, title, subtitle, message, meta }: Props) {
  return (
    <div className="pageHeader">
      <div>
        <p className="eyebrow">{eyebrow}</p>
        <h1>{title}</h1>
        <p className="subtitle">{subtitle}</p>
      </div>
      <div className="status">
        <span>{message}</span>
        {meta ? <span>{meta}</span> : null}
      </div>
    </div>
  )
}

// java-projects/JtProject-Vue/frontend/src/components/PageHeader.vue
<script setup lang="ts">
defineProps<{
  eyebrow: string
  title: string
  subtitle: string
  message: string
  meta?: string
}>()
</script>

<template>
  <div class="page-header">
    <div>
      <p class="tag">{{ eyebrow }}</p>
      <h1>{{ title }}</h1>
      <p class="lead">{{ subtitle }}</p>
    </div>
    <div class="rail">
      <span>{{ message }}</span>
      <span v-if="meta">{{ meta }}</span>
    </div>
  </div>
</template>
