// java-projects/JtProject-React/frontend/src/components/ProductManager.tsx
import type { FormEvent } from 'react'
import type { Category, Product } from '../types'

type ProductForm = {
  id: number
  name: string
  categoryId: number
  price: number
  weight: number
  quantity: number
  description: string
  image: string
}

type Props = {
  categories: Category[]
  products: Product[]
  productForm: ProductForm
  setProductForm: (value: ProductForm) => void
  onSubmit: (event: FormEvent) => void
  onDelete: (id: number) => void
}

export function ProductManager({ categories, products, productForm, setProductForm, onSubmit, onDelete }: Props) {
  return (
    <article className="panel">
      <h2>Product Editor</h2>
      <form onSubmit={onSubmit} className="form">
        <input value={productForm.name} onChange={(e) => setProductForm({ ...productForm, name: e.target.value })} placeholder="Product name" />
        <select value={productForm.categoryId} onChange={(e) => setProductForm({ ...productForm, categoryId: Number(e.target.value) })}>
          {categories.map((category) => (
            <option key={category.id} value={category.id}>{category.name}</option>
          ))}
        </select>
        <input value={productForm.price} type="number" onChange={(e) => setProductForm({ ...productForm, price: Number(e.target.value) })} placeholder="Price" />
        <input value={productForm.quantity} type="number" onChange={(e) => setProductForm({ ...productForm, quantity: Number(e.target.value) })} placeholder="Quantity" />
        <input value={productForm.weight} type="number" onChange={(e) => setProductForm({ ...productForm, weight: Number(e.target.value) })} placeholder="Weight" />
        <input value={productForm.image} onChange={(e) => setProductForm({ ...productForm, image: e.target.value })} placeholder="Image URL" />
        <textarea value={productForm.description} onChange={(e) => setProductForm({ ...productForm, description: e.target.value })} placeholder="Description" />
        <button type="submit">{productForm.id ? 'Update Product' : 'Create Product'}</button>
      </form>
      <div className="stack">
        {products.map((product) => (
          <div key={product.id} className="listRow">
            <span>{product.name}</span>
            <div className="inlineActions">
              <button className="ghost" onClick={() => setProductForm(productFormFromProduct(product))}>Edit</button>
              <button className="ghost" onClick={() => onDelete(product.id)}>Delete</button>
            </div>
          </div>
        ))}
      </div>
    </article>
  )
}

function productFormFromProduct(product: Product): ProductForm {
  return {
    id: product.id,
    name: product.name,
    categoryId: product.categoryId,
    price: product.price,
    weight: product.weight,
    quantity: product.quantity,
    description: product.description,
    image: product.image
  }
}

// java-projects/JtProject-Vue/frontend/src/components/ProductManager.vue
<script setup lang="ts">
import type { Category, Product } from '../types'

const props = defineProps<{
  categories: Category[]
  products: Product[]
  productForm: {
    id: number
    name: string
    categoryId: number
    price: number
    weight: number
    quantity: number
    description: string
    image: string
  }
}>()

defineEmits<{
  submit: []
  edit: [product: Product]
  delete: [id: number]
}>()
</script>

<template>
  <article class="panel">
    <h2>Product Studio</h2>
    <div class="stack">
      <input v-model="props.productForm.name" placeholder="Product name" />
      <select v-model.number="props.productForm.categoryId">
        <option v-for="category in props.categories" :key="category.id" :value="category.id">{{ category.name }}</option>
      </select>
      <input v-model.number="props.productForm.price" type="number" placeholder="Price" />
      <input v-model.number="props.productForm.quantity" type="number" placeholder="Quantity" />
      <input v-model.number="props.productForm.weight" type="number" placeholder="Weight" />
      <input v-model="props.productForm.image" placeholder="Image URL" />
      <textarea v-model="props.productForm.description" placeholder="Description" />
      <button @click="$emit('submit')">{{ props.productForm.id ? 'Update Product' : 'Create Product' }}</button>
    </div>
    <div class="stack">
      <div v-for="product in props.products" :key="product.id" class="list-row">
        <span>{{ product.name }}</span>
        <div class="actions">
          <button class="ghost" @click="$emit('edit', product)">Edit</button>
          <button class="ghost" @click="$emit('delete', product.id)">Delete</button>
        </div>
      </div>
    </div>
  </article>
</template>
