// java-projects/JtProject-React/frontend/src/components/UserAuthForms.tsx
import type { FormEvent } from 'react'
import type { RegisterForm, UserLoginForm } from '../services/appService'

type Props = {
  message: string
  userLogin: UserLoginForm
  registerForm: RegisterForm
  setUserLogin: (value: UserLoginForm) => void
  setRegisterForm: (value: RegisterForm) => void
  onLogin: (event: FormEvent) => void
  onRegister: (event: FormEvent) => void
}

export function UserAuthForms(props: Props) {
  const { message, userLogin, registerForm, setUserLogin, setRegisterForm, onLogin, onRegister } = props

  return (
    <>
      <p className="banner">{message}</p>
      <div className="split">
        <form onSubmit={onLogin} className="form">
          <h2>Login</h2>
          <input value={userLogin.username} onChange={(e) => setUserLogin({ ...userLogin, username: e.target.value })} placeholder="Username" />
          <input value={userLogin.password} type="password" onChange={(e) => setUserLogin({ ...userLogin, password: e.target.value })} placeholder="Password" />
          <button type="submit">登录</button>
        </form>
        <form onSubmit={onRegister} className="form">
          <h2>Register</h2>
          <input value={registerForm.username} onChange={(e) => setRegisterForm({ ...registerForm, username: e.target.value })} placeholder="New username" />
          <input value={registerForm.email} onChange={(e) => setRegisterForm({ ...registerForm, email: e.target.value })} placeholder="Email" />
          <input value={registerForm.password} type="password" onChange={(e) => setRegisterForm({ ...registerForm, password: e.target.value })} placeholder="Password" />
          <input value={registerForm.address} onChange={(e) => setRegisterForm({ ...registerForm, address: e.target.value })} placeholder="Address" />
          <button type="submit">注册并登录</button>
        </form>
      </div>
    </>
  )
}

// java-projects/JtProject-Vue/frontend/src/components/UserAuthForms.vue
<script setup lang="ts">
const props = defineProps<{
  message: string
  userLogin: { username: string; password: string }
  registerForm: { username: string; email: string; password: string; address: string }
}>()

defineEmits<{
  login: []
  register: []
}>()
</script>

<template>
  <p class="banner">{{ props.message }}</p>
  <div class="split">
    <div class="stack">
      <h2>Login</h2>
      <input v-model="props.userLogin.username" placeholder="Username" />
      <input v-model="props.userLogin.password" type="password" placeholder="Password" />
      <button @click="$emit('login')">登录</button>
    </div>
    <div class="stack">
      <h2>Register</h2>
      <input v-model="props.registerForm.username" placeholder="New username" />
      <input v-model="props.registerForm.email" placeholder="Email" />
      <input v-model="props.registerForm.password" type="password" placeholder="Password" />
      <input v-model="props.registerForm.address" placeholder="Address" />
      <button @click="$emit('register')">注册并登录</button>
    </div>
  </div>
</template>
